# Generated by Django 5.2.8 on 2025-11-19 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True, verbose_name='nome')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
            },
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Equipamento')),
                ('numero_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Série')),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('status', models.CharField(choices=[('EM_USO', 'Em uso'), ('ESTOQUE', 'Estoque'), ('MANUTENCAO', 'Manutenção')], default='ESTOQUE', max_length=10, verbose_name='Status do Equipamento')),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipamentos', to='inventario_TI.categoria', verbose_name='Categoria')),
            ],
            options={
                'verbose_name': 'Equipamento',
                'verbose_name_plural': 'Equipamentos',
            },
        ),
    ]
