# Generated by Django 5.2.8 on 2025-11-21 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario_TI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='cor',
        ),
        migrations.AlterField(
            model_name='equipamento',
            name='data_aquisicao',
            field=models.DateField(),
        ),
    ]
